/* CLAQUETE — data.js
   Catálogo mockado. Filmes: ids 1–12. Séries: ids 101–112.
   Para usar imagem real, preencha "poster" e/ou "backdrop" com um caminho
   relativo (ex.: "img/posters/1.jpg"). Vazio = gera pôster SVG automático. */

const CATALOGO = [
  /* ================= FILMES ================= */
  {
    id: 1,
    tipo: "filme",
    titulo: "Sal da Maré",
    ano: 2026,
    duracao: "112 min",
    genero: "Drama",
    diretor: "Helena Barreto",
    elenco: [
      "Marina Cavalcanti",
      "Otávio Brandão",
      "Lúcia Menezes",
      "Davi Sampaio",
    ],
    sinopse:
      "Uma pescadora do Recife descobre que o mangue onde cresceu será aterrado e decide enfrentar a família que sempre mandou na cidade. Entre a maré cheia e a maré vazia, ela precisa escolher o que está disposta a perder.",
    poster: "",
    backdrop: "",
  },
  {
    id: 2,
    tipo: "filme",
    titulo: "O Último Frevo",
    ano: 2025,
    duracao: "98 min",
    genero: "Musical",
    diretor: "Caetano Lyra",
    elenco: ["Ruy Albuquerque", "Beatriz Tavares", "Ícaro Nóbrega"],
    sinopse:
      "Na última noite de carnaval antes de o clube fechar as portas, um maestro aposentado reúne a velha orquestra para uma apresentação que ninguém acreditava ser possível.",
    poster: "",
    backdrop: "",
  },
  {
    id: 3,
    tipo: "filme",
    titulo: "Cinza Elétrico",
    ano: 2026,
    duracao: "134 min",
    genero: "Ficção científica",
    diretor: "Ingrid Vasconcelos",
    elenco: [
      "Tiago Ramalho",
      "Yara Nascimento",
      "Edgar Pontes",
      "Lia Cordeiro",
    ],
    sinopse:
      "Em uma cidade que perdeu a eletricidade há dez anos, uma engenheira encontra o último gerador funcionando e percebe que alguém o mantém ligado de propósito. Ligar o aparelho pode salvar todos ou chamar quem os apagou.",
    poster: "",
    backdrop: "",
  },
  {
    id: 4,
    tipo: "filme",
    titulo: "A Casa dos Ventos",
    ano: 2024,
    duracao: "105 min",
    genero: "Drama",
    diretor: "Samuel Dornelas",
    elenco: ["Aurora Veloso", "Mateus Guedes", "Dona Nair Pessoa"],
    sinopse:
      "Três irmãos voltam à casa de infância no litoral para vendê-la e encontram, dentro das paredes, cartas que reescrevem a história da família.",
    poster: "",
    backdrop: "",
  },
  {
    id: 5,
    tipo: "filme",
    titulo: "Meridiano Zero",
    ano: 2025,
    duracao: "121 min",
    genero: "Thriller",
    diretor: "Renata Quintela",
    elenco: [
      "Felipe Aragão",
      "Camila Soares",
      "Heitor Lacerda",
      "Vânia Duarte",
    ],
    sinopse:
      "Um cartógrafo recebe um mapa que muda de forma a cada vez que é aberto. Quando um dos pontos marcados coincide com um crime, ele vira o principal suspeito.",
    poster: "",
    backdrop: "",
  },
  {
    id: 6,
    tipo: "filme",
    titulo: "Quarto 9",
    ano: 2023,
    duracao: "92 min",
    genero: "Terror",
    diretor: "Bruno Falcão",
    elenco: ["Nina Teixeira", "Caio Medeiros", "Sérgio Paiva"],
    sinopse:
      "Uma recepcionista noturna de um hotel antigo percebe que o quarto 9, trancado há anos, recebe um hóspede toda sexta-feira às 3h da manhã.",
    poster: "",
    backdrop: "",
  },
  {
    id: 7,
    tipo: "filme",
    titulo: "Paralelepípedo",
    ano: 2024,
    duracao: "96 min",
    genero: "Comédia",
    diretor: "Lívia Montenegro",
    elenco: ["Genilson Prado", "Tânia Rocha", "Zeca Almeida", "Pietra Lins"],
    sinopse:
      "Quando a prefeitura decide trocar o calçamento de uma rua histórica, os moradores inventam um tombamento falso. A mentira cresce mais rápido do que o buraco.",
    poster: "",
    backdrop: "",
  },
  {
    id: 8,
    tipo: "filme",
    titulo: "Rio Seco",
    ano: 2022,
    duracao: "118 min",
    genero: "Faroeste",
    diretor: "Joaquim Aranha",
    elenco: ["Raimundo Calado", "Elisa Barros", "Abel Fontes"],
    sinopse:
      "No sertão de uma seca que dura sete anos, um ex-vaqueiro escolta uma carroça de água por território de bando. A carga vale mais do que qualquer ouro.",
    poster: "",
    backdrop: "",
  },
  {
    id: 9,
    tipo: "filme",
    titulo: "Faróis de Itamaracá",
    ano: 2026,
    duracao: "109 min",
    genero: "Mistério",
    diretor: "Paula Rangel",
    elenco: ["Dora Siqueira", "Leandro Maia", "Cláudio Neves", "Rosa Telles"],
    sinopse:
      "Uma faroleira herda o posto da avó e descobre um diário com horários de navios que nunca existiram. Todos os registros terminam na mesma data: amanhã.",
    poster: "",
    backdrop: "",
  },
  {
    id: 10,
    tipo: "filme",
    titulo: "Madrugada em Olinda",
    ano: 2023,
    duracao: "101 min",
    genero: "Romance",
    diretor: "Tomás Pedrosa",
    elenco: ["Clara Montefusco", "Rafael Aquino"],
    sinopse:
      "Duas pessoas que se conhecem numa ladeira às 4h da manhã têm até o nascer do sol para decidir se aquilo foi só uma noite ou o começo de outra vida.",
    poster: "",
    backdrop: "",
  },
  {
    id: 11,
    tipo: "filme",
    titulo: "Ferro e Poeira",
    ano: 2021,
    duracao: "127 min",
    genero: "Ação",
    diretor: "Marcos Vilela",
    elenco: ["Dante Ribas", "Joana Kuster", "Wagner Lopes", "Ester Fialho"],
    sinopse:
      "Um maquinista aposentado é obrigado a conduzir uma última viagem de trem de carga, sabendo que há algo na composição que muita gente quer impedir de chegar.",
    poster: "",
    backdrop: "",
  },
  {
    id: 12,
    tipo: "filme",
    titulo: "Lição de Abismo",
    ano: 2025,
    duracao: "114 min",
    genero: "Drama",
    diretor: "Alice Montalvão",
    elenco: ["Sônia Bittencourt", "Gustavo Reis", "Lauro Tenório"],
    sinopse:
      "Uma professora de matemática aceita dar aulas particulares a um aluno que não fala desde o acidente do pai. O método que ela inventa para alcançá-lo muda os dois.",
    poster: "",
    backdrop: "",
  },

  /* ================= SÉRIES ================= */
  {
    id: 101,
    tipo: "serie",
    titulo: "Maré Alta",
    ano: 2026,
    duracao: "3 temporadas · 8 episódios de 52 min",
    genero: "Drama",
    diretor: "Criação de Helena Barreto",
    elenco: [
      "Marina Cavalcanti",
      "Otávio Brandão",
      "Dalva Pires",
      "Jonas Ferraz",
    ],
    sinopse:
      "Famílias de um porto pesqueiro disputam o controle do cais enquanto o nível do mar sobe, ano após ano, sobre o que elas julgavam ser delas.",
    poster: "",
    backdrop: "",
  },
  {
    id: 102,
    tipo: "serie",
    titulo: "Código Cajueiro",
    ano: 2025,
    duracao: "2 temporadas · 10 episódios de 45 min",
    genero: "Suspense",
    diretor: "Criação de Rafael Quaresma",
    elenco: ["Bianca Serpa", "Adriano Muniz", "Olga Prestes"],
    sinopse:
      "Uma analista de dados recebe mensagens cifradas escondidas em notas fiscais de uma cooperativa de cajus e descobre um esquema que passa por três estados.",
    poster: "",
    backdrop: "",
  },
  {
    id: 103,
    tipo: "serie",
    titulo: "Herdeiros do Sertão",
    ano: 2024,
    duracao: "4 temporadas · 12 episódios de 50 min",
    genero: "Drama",
    diretor: "Criação de Joaquim Aranha",
    elenco: [
      "Raimundo Calado",
      "Elisa Barros",
      "Neuza Cabral",
      "Pedro Lustosa",
    ],
    sinopse:
      "Quando o coronel morre sem deixar testamento, filhos legítimos e filhos de criação disputam terra, gado e a verdade sobre o passado.",
    poster: "",
    backdrop: "",
  },
  {
    id: 104,
    tipo: "serie",
    titulo: "Estação Fantasma",
    ano: 2023,
    duracao: "2 temporadas · 6 episódios de 40 min",
    genero: "Terror",
    diretor: "Criação de Bruno Falcão",
    elenco: ["Nina Teixeira", "Ramiro Costa", "Helga Vidal"],
    sinopse:
      "Uma equipe de manutenção do metrô percebe que há uma estação que não aparece em nenhum mapa, mas aparece no trajeto de quem trabalha de madrugada.",
    poster: "",
    backdrop: "",
  },
  {
    id: 105,
    tipo: "serie",
    titulo: "Linha 14",
    ano: 2026,
    duracao: "1 temporada · 8 episódios de 48 min",
    genero: "Policial",
    diretor: "Criação de Daniela Fortuna",
    elenco: ["Wesley Amaral", "Karina Beltrão", "Moacir Tuma", "Letícia Hora"],
    sinopse:
      "Dois motoristas de ônibus da mesma linha testemunham, por ângulos opostos, um crime que a cidade prefere esquecer. Só um deles está dizendo a verdade.",
    poster: "",
    backdrop: "",
  },
  {
    id: 106,
    tipo: "serie",
    titulo: "Brasa Viva",
    ano: 2025,
    duracao: "3 temporadas · 10 episódios de 55 min",
    genero: "Gastronomia",
    diretor: "Criação de Tereza Paiva",
    elenco: ["Chef Amélia Rocha", "Diogo Mattos", "Fátima Gouveia"],
    sinopse:
      "Em uma churrascaria de beira de estrada à beira da falência, a nova cozinheira-chefe tem uma temporada para salvar o negócio e a relação com o pai.",
    poster: "",
    backdrop: "",
  },
  {
    id: 107,
    tipo: "serie",
    titulo: "Noite no Mercado",
    ano: 2024,
    duracao: "2 temporadas · 8 episódios de 30 min",
    genero: "Comédia",
    diretor: "Criação de Lívia Montenegro",
    elenco: [
      "Genilson Prado",
      "Tânia Rocha",
      "Beto Sarmento",
      "Cecília Dantas",
    ],
    sinopse:
      "Os feirantes de um mercado público que nunca fecha lidam com fregueses, fiscais e uma lenda urbana que atrapalha as vendas.",
    poster: "",
    backdrop: "",
  },
  {
    id: 108,
    tipo: "serie",
    titulo: "Delegacia das Dunas",
    ano: 2022,
    duracao: "5 temporadas · 10 episódios de 45 min",
    genero: "Policial",
    diretor: "Criação de Márcio Teles",
    elenco: ["Armando Ferrer", "Soraia Lima", "Cacá Bezerra"],
    sinopse:
      "Num balneário que triplica de população no verão, uma delegada de poucos recursos resolve crimes que a alta temporada tenta esconder.",
    poster: "",
    backdrop: "",
  },
  {
    id: 109,
    tipo: "serie",
    titulo: "Anel de Sal",
    ano: 2026,
    duracao: "1 temporada · 6 episódios de 58 min",
    genero: "Ficção científica",
    diretor: "Criação de Ingrid Vasconcelos",
    elenco: ["Yara Nascimento", "Tiago Ramalho", "Dr. Osmar Veiga"],
    sinopse:
      "Um círculo de sal surge ao redor de uma salina no Rio Grande do Norte. Quem entra volta sabendo coisas que ainda vão acontecer.",
    poster: "",
    backdrop: "",
  },
  {
    id: 110,
    tipo: "serie",
    titulo: "Distrito Zero",
    ano: 2023,
    duracao: "3 temporadas · 9 episódios de 50 min",
    genero: "Ação",
    diretor: "Criação de Marcos Vilela",
    elenco: ["Dante Ribas", "Joana Kuster", "Hugo Brasil", "Mirela Santos"],
    sinopse:
      "Uma unidade especial é enviada para um bairro isolado por uma quarentena que ninguém explica, e logo percebe que o inimigo está dentro do próprio grupo.",
    poster: "",
    backdrop: "",
  },
  {
    id: 111,
    tipo: "serie",
    titulo: "Cartas de Boa Viagem",
    ano: 2025,
    duracao: "2 temporadas · 8 episódios de 42 min",
    genero: "Romance",
    diretor: "Criação de Tomás Pedrosa",
    elenco: ["Clara Montefusco", "Rafael Aquino", "Vera Lúcia Arraes"],
    sinopse:
      "Em cada episódio, uma carta antiga encontrada num sebo do Recife conta o começo de um amor e deixa uma pergunta sobre o fim.",
    poster: "",
    backdrop: "",
  },
  {
    id: 112,
    tipo: "serie",
    titulo: "A Fábrica de Sonhos",
    ano: 2021,
    duracao: "4 temporadas · 10 episódios de 50 min",
    genero: "Drama",
    diretor: "Criação de Alice Montalvão",
    elenco: [
      "Sônia Bittencourt",
      "Gustavo Reis",
      "Leda Mourão",
      "Franklin Cruz",
    ],
    sinopse:
      "Uma tecelagem de Paulista, entre a crise e a modernização, é o palco de quatro gerações de operárias e das escolhas que moldaram a cidade.",
    poster: "",
    backdrop: "",
  },
];

/* Home: ids em destaque */
const DESTAQUE_ID = 3;
const TOP3_IDS = [3, 101, 1];
